### ISSUE TITLE
no-std builds are not working and are checked incorrectly

### ISSUE THREAD

**Issue by waywardmonkeys** [googlefonts/fontations#1006]
CI checks `no-std` builds for `font-types`, `read-fonts` and `skrifa`. However, it uses the default target which has an `std`, so this isn't a comprehensive check.

These jobs need to specify a target and that needs to not have an `std` implementation. I tend to use one of `thumbv7m-none-eabi`, `riscv64imac-unknown-none-elf`, or `x86_64-unknown-none`.

The `rust-toolchain` action will have to install this target:

```
  check-no-std:
    name: cargo check no std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@stable
            with:
                targets: riscv64imac-unknown-none-elf

      - name: cargo check font-types
        run: cargo check --manifest-path=font-types/Cargo.toml --no-default-features --target riscv64imac-unknown-none-elf

      - name: cargo check read-fonts
        run: cargo check --manifest-path=read-fonts/Cargo.toml --no-default-features --features=libm --target riscv64imac-unknown-none-elf

      - name: cargo check skrifa
        run: cargo check --manifest-path=skrifa/Cargo.toml --no-default-features --features=libm --target riscv64imac-unknown-none-elf
```

Once you do that, you'll see that `int-set` doesn't build for `no-std` and therefore `read-fonts` doesn't build for `no-std`.
