### ISSUE TITLE
Release on tag?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontations#160]
We have a nice rig (https://googlefonts.github.io/python.html#make-a-release) for releasing python by pushing a tag, can we have something similar - ideally exactly the same for the user - for Rust?

**Comment by chrissimpkins** [comment]
This is an example of automated **GitHub releases** filtered on git tags in a Rust project (source language isn't important if you are only releasing source archives): https://github.com/chrissimpkins/vectora/blob/main/.github/workflows/publish-release.yml

Something like this might work for the automated cargo publish step if you intend to push to crates.io at git version tag push: https://github.com/marketplace/actions/publish-crates

GH Actions workflows can be defined with execution [filtered on a version formatted git tag](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore). 

e.g. at the head of your workflow definition, 

```yaml
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v9.000 and v10.001rc1
```
