### ISSUE TITLE
Provide an easy way to run a subset of codegen targets

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontations#69]
Right now if I want to repeatedly regenerate the same table I copy codegen_plan.toml and make one with just what I want, e.g.

```toml
[[generate]]
mode = "parse"
source = "resources/codegen_inputs/cpal.rs"
target = "read-fonts/generated/generated_cpal.rs"
```

This doesn't work well because it seemingly deletes read/write-fonts/generated/* regardless of whether the plan touches the files in question.

It would be nice to be able to run the normal codegen and tell it "only do this/these items" such as by regex on the source or target. At a glance I think just filtering in `fn run_plan(path: &Path)` might do it?
